### ISSUE TITLE
Not building Routes anymore

### ISSUE THREAD

**Issue by chrisfx606** [projectlistick/listick_fake_gps#3]
Listick isn't building routes anymore, it builds a straight line instead. I'm guessing there is some internet service issue.
But it would be nice if it would show a popup in that case.

Tested on Xiaomi Redmi 5 plus and Wiko Power U20

**Comment by so-lli** [comment]
The problem of building a route and determining an altitude occurred on our backend. We have already fixed all the problems. 
Thanks for the feedback!

**Comment by AlbertShen0211** [comment]
MapsPresenter.java:53: 错误: 找不到符号
import project.listick.fakegps.DeviceUtils;
                              ^
  符号:   类 DeviceUtils
  位置: 程序包 project.listick.fakegps
