### ISSUE TITLE
Consider making the project open-source

### ISSUE THREAD

**Issue by Nonononoki** [projectlistick/listick_fake_gps#8]
As this project has not received any updates in a year, you should consider relicense the code under an open-source license where the community can pick it up and add additional features and bugfixes and also release it on F-droid. My recommendation would be the GPLv3, where any changes need to be under the same license as well.

**Comment by imsourcandy** [comment]
Thanks for creating an Issue. This is really sounds good, I think we will accept it from the next update

**Comment by grkmcngns** [comment]
Apk please brom ♥️
