### ISSUE TITLE
App fails at hiding mock locations

### ISSUE THREAD

**Issue by ADFLive** [projectlistick/listick_fake_gps#9]
Hello,
I know that every mock location app, on unroot devices needs dev settings and mock settings set on the mock app.
Obviously 99% of the apps easily detects if the location is spoofed by looking at isMock and isFromMockProvider, so the user who really wants to mock location without being detected should root his device and edit the framework.jar
I edited the framework.jar using SmaliPatcherEx so that mock apps may hide mock location, and even better the possibility to mock locations without enabling dev settings (and granting mock settings to the app).
Unfortunately Listick, with all the modifications mentioned above, can't hide mock locations and also can't be used without dev tools being enabled.
I believe that the app should consider a way to hide itself, what SmaliPatcherEx does should facilitate the job.

Tested on xiaomi fuxi HyperOS android 14 rooted with Magisk Alpha

Listick Fake GPS beta 3.1

![Screenshot_2024-11-01-11-15-46-115_com miui home-edit](https://github.com/user-attachments/assets/502e57ae-b193-4ce3-8dd2-941879d8dd67)

**Comment by imsourcandy** [comment]
As far as I know, SmaliPatcher patches some functions in Android location & app ops manager. 
When you patch [MockLocationProvider.java#57](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/services/core/java/com/android/server/location/provider/MockLocationProvider.java#57), there shouldn't be any difference in which app you use for location spoofing purposes. Both isFromMockProvider & isMock should return false, regardless of the app.

Besides, Listick Fake GPS also enables mock mode in the Google's Fused Location Provider, which doesn't rely on Android's MockLocationProvider. So, I think you might want to try disabling Google's Fused Locations Provider.

**Comment by ADFLive** [comment]
Hi, thanks for your reply.
First of all, I appreciate your hard work, leaving aside that issue the app itself works well.
I'm not an expert at all but essentially SmaliPatcher should edit and patch MockLocationProvider (android>server >location>provider>MockLocationProvider) and SystemAppOpsHelper (android>server >location>injector>SystemAppOpsHelper) both located in the system framework.jar
Editing some strings in a way that both isMock and isFromMockProvider return always false.
As you said Google Fused Location Provider doesn't rely on MockLocationProvider so the previously mentioned modifications aren't useful to hide spoofing when Listick Fake GPS is active.
I don't know if there is a possibility to make similar patches to the Google Fused Location Provider and if there was any chance that implicates making modifications to the Google Play Services app which should be very hard (and break APIs like Play Integrity).
By my opinion, there should be a option in the app to only spoofing with MockLocationProvider (or just make it the default mode), I tested apps that theoretically only uses MockLocationProvider to spoof, isMock and isFromMockProvider return false and no compatibility issue with Google's Fused Location Provider APIs (just rubberbanding from real to fake location, but I can easily solve it by disabling Google Location Accuracy)

**Comment by imsourcandy** [comment]
Any system modifications will break Play Integrity and other security mechanisms. As you mentioned, hiding the spoofing in the Fused Location Provider requires modifying Play Services. In the next version, I will add the option to disable the Fused Provider.
